let store = {
    ads: [
        {
            id: 1,
            carMark: 'BMW',
            carModel: 'M5',
            carGeneration: 'V (F10)',
            bodyType: 'Седан',
            driveUnit: 'Задний',
            fuelType: 'Бензин',
            transmission: 'Робот',
            color: 'Синий',
            engineСapacity: '4.4 л',
            enginePower: '560 л.с.',
            year: '2013',
            mileage: '60 000 км',
            costBYN: '98 600 BYN',
            costUSD: '0',
            costEUR: '0'
        },
        {
            id: 2,
            carMark: 'Mercedes-Benz',
            carModel: 'S-class 65 AMG',
            carGeneration: 'W222',
            bodyType: 'Седан',
            driveUnit: 'Задний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Белый',
            engineСapacity: '6.0 л',
            enginePower: '630 л.с.',
            year: '2015',
            mileage: '40 000 км',
            costBYN: '256 000 BYN',
            costUSD: '0',
            costEUR: '0'
        },
	{
            id: 3,
            carMark: 'Lexus',
            carModel: 'RX 330',
            carGeneration: '2',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '3.3 л',
            enginePower: '287 л.с.',
            year: '2004',
            mileage: '200 000 км',
            costBYN: '30000 BYN',
            costUSD: '10000',
            costEUR: '0'
        },        
        {
            id: 4,
            carMark: 'Lexus',
            carModel: 'GS 460',
            carGeneration: '3',
            bodyType: 'Седан',
            driveUnit: 'Задний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Синий',
            engineСapacity: '4.6 л',
            enginePower: '367 л.с.',
            year: '2009',
            mileage: '120 000 км',
            costBYN: '40 000 BYN',
            costUSD: '16 000',
            costEUR: '0'
        },        
	{
            id: 5,
            carMark: 'Toyota',
            carModel: 'Camry 350',
            carGeneration: '8',
            bodyType: 'Седан',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '3.5 л',
            enginePower: '267 л.с.',
            year: '2018',
            mileage: '67 000 км',
            costBYN: '50 000 BYN',
            costUSD: '20 000',
            costEUR: '0'
        },
        {
            id: 6,
            carMark: 'Lexus',
            carModel: 'ES 250',
            carGeneration: '4',
            bodyType: 'Седан',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Белый',
            engineСapacity: '2.5 л',
            enginePower: '207 л.с.',
            year: '2020',
            mileage: '1 000 км',
            costBYN: '60 BYN',
            costUSD: '28 000',
            costEUR: '0'
        },
        {
            id: 7,
            carMark: 'Lexus',
            carModel: 'LX 570',
            carGeneration: '3',
            bodyType: 'Внедорожник',
            driveUnit: 'Непостоянный полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный металлик',
            engineСapacity: '5.7 л',
            enginePower: '367 л.с.',
            year: '2009',
            mileage: '157 000 км',
            costBYN: '60 000 BYN',
            costUSD: '28 000',
            costEUR: '0'
        },
        {
            id: 8,
            carMark: 'Nissan',
            carModel: 'X-trail',
            carGeneration: '4',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Синий металлик',
            engineСapacity: '2.0 л',
            enginePower: '187 л.с.',
            year: '2018',
            mileage: '40 000 км',
            costBYN: '56 000 BYN',
            costUSD: '21 000',
            costEUR: '0'
        },
        {
            id: 9,
            carMark: 'Infinity',
            carModel: 'FX 35',
            carGeneration: '1',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Коричневый',
            engineСapacity: '3.5 л',
            enginePower: '280 л.с.',
            year: '2005',
            mileage: '150 000 км',
            costBYN: '18 000 BYN',
            costUSD: '8 000',
            costEUR: '0'
        },
        {
            id: 10,
            carMark: 'Infinity',
            carModel: 'QX 56',
            carGeneration: '2',
            bodyType: 'Внедорожник',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Белый',
            engineСapacity: '5.6 л',
            enginePower: '405 л.с.',
            year: '2011',
            mileage: '117 000 км',
            costBYN: '50 000 BYN',
            costUSD: '24 000',
            costEUR: '0'
        },
        {
            id: 11,
            carMark: 'Audi',
            carModel: 'A7',
            carGeneration: '1',
            bodyType: 'Лифтбек',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Белый',
            engineСapacity: '2.8 л',
            enginePower: '204 л.с.',
            year: '2013',
            mileage: '135 000 км',
            costBYN: '42 000 BYN',
            costUSD: '20 000',
            costEUR: '0'
        },
        {
            id: 12,
            carMark: 'Lexus',
            carModel: 'RX 350',
            carGeneration: '3',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '3.5 л',
            enginePower: '277 л.с.',
            year: '2010',
            mileage: '110 000 км',
            costBYN: '46 000 BYN',
            costUSD: '22 000',
            costEUR: '0'
        },
        {
            id: 13,
            carMark: 'Lexus',
            carModel: 'RX 300',
            carGeneration: '4',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Белый',
            engineСapacity: '2.0 л',
            enginePower: '238 л.с.',
            year: '2019',
            mileage: '10 км',
            costBYN: '125 000 BYN',
            costUSD: '60 000',
            costEUR: '0'
        },
        {
            id: 14,
            carMark: 'Lexus',
            carModel: 'GX 460',
            carGeneration: '2',
            bodyType: 'Внедорожник',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Белый',
            engineСapacity: '4.6 л',
            enginePower: '296 л.с.',
            year: '2014',
            mileage: '68 000 км',
            costBYN: '88 000 BYN',
            costUSD: '40 000',
            costEUR: '0'
        },
        {
            id: 15,
            carMark: 'Lexus',
            carModel: 'LS 500',
            carGeneration: '5',
            bodyType: 'Седан',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Серый',
            engineСapacity: '3.4 л',
            enginePower: '421 л.с.',
            year: '2018',
            mileage: '42 000 км',
            costBYN: '200 000 BYN',
            costUSD: '95 000',
            costEUR: '0'
        },
        {
            id: 16,
            carMark: 'Lexus',
            carModel: 'LS 460',
            carGeneration: '4',
            bodyType: 'Седан',
            driveUnit: 'Задний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Красный',
            engineСapacity: '4.6 л',
            enginePower: '380 л.с.',
            year: '2006',
            mileage: '250 000 км',
            costBYN: '30 000 BYN',
            costUSD: '14 000',
            costEUR: '0'
        },
        {
            id: 17,
            carMark: 'Lexus',
            carModel: 'RX 300',
            carGeneration: '1',
            bodyType: 'Кроссовер',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '3.0 л',
            enginePower: '223 л.с.',
            year: '2000',
            mileage: '207 000 км',
            costBYN: '14 000 BYN',
            costUSD: '6 000',
            costEUR: '0'
        },
        {
            id: 18,
            carMark: 'Infinity',
            carModel: 'G 25',
            carGeneration: '4',
            bodyType: 'Седан',
            driveUnit: 'Задний',
            fuelType: 'Дизель',
            transmission: 'Автомат',
            color: 'Синий',
            engineСapacity: '2.5 л',
            enginePower: '222 л.с.',
            year: '2011',
            mileage: '126 000 км',
            costBYN: '22 000 BYN',
            costUSD: '10 000',
            costEUR: '0'
        },
        {
            id: 19,
            carMark: 'Nissan',
            carModel: 'Almera',
            carGeneration: '2',
            bodyType: 'Седан',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Серый',
            engineСapacity: '1.8 л',
            enginePower: '114 л.с.',
            year: '2002',
            mileage: '270 000 км',
            costBYN: '4 200 BYN',
            costUSD: '2 000',
            costEUR: '0'
        },
        {
            id: 20,
            carMark: 'Audi',
            carModel: 'A6',
            carGeneration: '3',
            bodyType: 'Универсал',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Синий',
            engineСapacity: '2.8 л',
            enginePower: '210 л.с.',
            year: '2008',
            mileage: '200 000 км',
            costBYN: '20 000 BYN',
            costUSD: '9 000',
            costEUR: '0'
        },
        {
            id: 21,
            carMark: 'Audi',
            carModel: 'Q8',
            carGeneration: '1',
            bodyType: 'Внедорожник',
            driveUnit: 'Полный',
            fuelType: 'Дизель',
            transmission: 'Автомат',
            color: 'Серый',
            engineСapacity: '3.0 л',
            enginePower: '249 л.с.',
            year: '2019',
            mileage: '7 000 км',
            costBYN: '198 000 BYN',
            costUSD: '90 000',
            costEUR: '0'
        },
        {
            id: 22,
            carMark: 'Audi',
            carModel: 'Q3',
            carGeneration: '1',
            bodyType: 'Кроссовер',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Робот',
            color: 'Коричневый',
            engineСapacity: '1.4 л',
            enginePower: '150 л.с.',
            year: '2015',
            mileage: '82 000 км',
            costBYN: '30 000 BYN',
            costUSD: '14 000',
            costEUR: '0'
        },
        {
            id: 23,
            carMark: 'Toyota',
            carModel: 'Corolla',
            carGeneration: '12',
            bodyType: 'Седан',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Вариатор',
            color: 'Белый',
            engineСapacity: '1.6 л',
            enginePower: '122 л.с.',
            year: '2019',
            mileage: '7 000 км',
            costBYN: '43 000 BYN',
            costUSD: '21 000',
            costEUR: '0'
        },
        {
            id: 24,
            carMark: 'Toyota',
            carModel: 'RAV4',
            carGeneration: '4',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Дизель',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '2.2 л',
            enginePower: '150 л.с.',
            year: '2017',
            mileage: '60 000 км',
            costBYN: '45 000 BYN',
            costUSD: '22 000',
            costEUR: '0'
        },
        {
            id: 25,
            carMark: 'Toyota',
            carModel: 'Sequoia',
            carGeneration: '2',
            bodyType: 'Внедорожник',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '5.7 л',
            enginePower: '381 л.с.',
            year: '2019',
            mileage: '60 км',
            costBYN: '320 000 BYN',
            costUSD: '150 000',
            costEUR: '0'
        },
        {
            id: 26,
            carMark: 'Toyota',
            carModel: 'Land Cruiser',
            carGeneration: '100 Series',
            bodyType: 'Внедорожник',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Серый',
            engineСapacity: '4.7 л',
            enginePower: '235 л.с.',
            year: '2000',
            mileage: '310 000 км',
            costBYN: '30 000 BYN',
            costUSD: '14 000',
            costEUR: '0'
        },
        {
            id: 27,
            carMark: 'Toyota',
            carModel: 'Land Cruiser',
            carGeneration: '200 Series',
            bodyType: 'Внедорожник',
            driveUnit: 'Полный',
            fuelType: 'Дизель',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '4.5 л',
            enginePower: '249 л.с.',
            year: '2016',
            mileage: '77 000 км',
            costBYN: '130 000 BYN',
            costUSD: '60 000',
            costEUR: '0'
        },
        {
            id: 28,
            carMark: 'Toyota',
            carModel: 'Camry 250',
            carGeneration: '8',
            bodyType: 'Седан',
            driveUnit: 'Передний',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '2.5 л',
            enginePower: '181 л.с.',
            year: '2018',
            mileage: '21 000 км',
            costBYN: '61 000 BYN',
            costUSD: '29 000',
            costEUR: '0'
	},
        {
            id: 29,
            carMark: 'Lexus',
            carModel: 'Rx 300',
            carGeneration: '2',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Чёрный',
            engineСapacity: '3.0 л',
            enginePower: '204 л.с.',
            year: '2005',
            mileage: '280 000 км',
            costBYN: '25 000 BYN',
            costUSD: '12 000',
            costEUR: '0'
        },
        {
            id: 30,
            carMark: 'Lexus',
            carModel: 'Rx 350',
            carGeneration: '2',
            bodyType: 'Кроссовер',
            driveUnit: 'Полный',
            fuelType: 'Бензин',
            transmission: 'Автомат',
            color: 'Бежевый',
            engineСapacity: '3.5 л',
            enginePower: '276 л.с.',
            year: '2008',
            mileage: '197 000 км',
            costBYN: '25 000 BYN',
            costUSD: '12 000',
            costEUR: '0'
        }
    ],
    users: [
        {
            id: 1,
            name: 'Глеб',
            email: 'andreev.gs12@yandex.by',
            phoneNumber: '+375447903119',
            city: 'Минск',
            drivingExperience: 'Без опыта',
            dateOfBirth: '12.04.2001',
            about: ''
        }
    ]
}

module.exports = store;